@startuml pacman
skinparam classAttributeIconSize 0

Character <|-- Pacman
Character <|-- Monster

abstract class Character {
    - Position: PVector
    - direction: int
    - NextDirection: int
    - spped: float

    - images: PImage[]
    - cur_animation: int
    - SIZE: PVector
    - ANIMETION_NUM: int
    - IMAGE_NAME: string

    + Character()
    + getPosition(): PVector
    + getDirection(): int
    + setNextDirection(nextDirection: int)
    + getSpeed(): float
    + setSpeed(speed: float)
    + move()
}

class Pacman {
    - invincible: boolean

    + Panman()
    + becomeInvincible()
}

class Monster {
    - ijike: boolean

    + Monster()
    + becomeIjike()
}

class Stage {
    - map: int[][]
}
@enduml